import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQueryClientProvider } from "./component/ReactQueryClientProvider";
const inter = Inter({ subsets: ["latin"] });
import Navbar from "./component/navbar";
export const metadata: Metadata = {
  title: "nextapp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <ReactQueryClientProvider>

    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
      </body>
    </html>
    </ReactQueryClientProvider>
  );
}
