import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQueryClientProvider } from "./component/ReactQueryClientProvider";
import Header from "./component/Header";
const inter = Inter({ subsets: ["latin"] });
// import Navbar from "./component/navbar";
export const metadata: Metadata = {
  title: "nextapp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    
    <html lang="en">
      <body className={inter.className}>
      <ReactQueryClientProvider>
        <Header/>
        {children}
    </ReactQueryClientProvider>
      </body>
    </html>
  );
}
